### ISSUE TITLE
[BUG]: White screen

### ISSUE THREAD

**Issue by headassbtw** [BalintCsala/VulkaniteDemoPack#10]
Probably a Linux Moment
Consistently reproducible, across resource packs and game restarts

The world renders as white, UI works perfectly fine though
![image](https://github.com/BalintCsala/VulkaniteDemoPack/assets/16214950/a12c08e1-1ca5-4d53-8a2b-d64cb6c70ad9)
I have a PBR resource pack installed, enabling/disabling that did not change anything

Specs:
- Radeon RX 6900 XT
- Ryzen 9 5900x
- 48GB DDR4

**Comment by BalintCsala** [comment]
This is a vulkanite issue, not a shader one

**Comment by headassbtw** [comment]
thanks for clarifying, figured it was shader because the game displayed fine without it, my bad
