### ISSUE TITLE
[BUG]: I don't know what causes this but, I'll link an image of how it looks for me

### ISSUE THREAD

**Issue by Kimizuky** [BalintCsala/VulkaniteDemoPack#11]
You _must_ include the following details:

- The game simply looks..interesting to say the least
- Visual
- I9 13900k, RTX 4090
![2024-03-18_18 47 59](https://github.com/BalintCsala/VulkaniteDemoPack/assets/163897583/3c29a7ab-77c3-43b6-aae6-1d45384f774b)

**Comment by BalintCsala** [comment]
Pretty sure you just don't have a pbr capable resourcepack. Load one in and completely restart the game.

**Comment by Kimizuky** [comment]
I didn knew that I had to load the resource pack, and then restart, worked now, all lights have those strange black dots everywhere, but very promising, this has much potential, sorry for the trouble.
