### ISSUE TITLE
[BUG]: Visual glitch and malfunctioning

### ISSUE THREAD

**Issue by Stehsaer** [BalintCsala/VulkaniteDemoPack#5]
See https://github.com/MCRcortex/vulkanite/issues/22

Spec: i7-13620H, RTX 4060 Laptop GPU (8gigs of vram, vulkanite uses 2gigs), driver version Nvidia Studio Driver 537.42, system Windows 11 Professional 22H2 22621.2134
Minecraft 1.20.1, Sodium 0.5.8, Iris v1.6.8

Mod list:
appleskin mc1.20 2.5.0
durability mc1.20 1.10.5
dynamic fps mc1.20 3.2.0
entityculling mc1.20.1 1.6.2
fabric api 0.89+1.20.1
fabric-language-kotlin
imblockerfabric 1.0.24
Jade mc1.20 11.6.0
journeymap mc1.20 5.9.8
libIPN mc1.20 3.0.2
modmenu 7.0.1
pinglist 1.4
vulkanite, sodium, iris

Screenshots: 
![2023-09-24_10 49 37](https://github.com/BalintCsala/VulkaniteDemoPack/assets/54050160/740b01b1-00ab-40ee-b2f5-daf35a601e35)
![2023-09-24_10 45 22](https://github.com/BalintCsala/VulkaniteDemoPack/assets/54050160/8cc3cc31-fd5d-47a9-b040-dd42b72a7c31)
![2023-09-24_10 45 29](https://github.com/BalintCsala/VulkaniteDemoPack/assets/54050160/9d4ecae6-de0b-43f5-bce3-46de42c67c88)
![2023-09-24_10 47 39](https://github.com/BalintCsala/VulkaniteDemoPack/assets/54050160/3d77f799-b54d-4f7e-860e-ab713892928e)

https://github.com/BalintCsala/VulkaniteDemoPack/assets/54050160/e6e5945b-bd74-4e83-9996-54567e16d794

**Comment by BalintCsala** [comment]
You didn't load in a PBR compatible resourcepack, even with saner fallbacks there'd be close to no point in this shaderpack without them so I won't support it.

**Comment by Stehsaer** [comment]
> You didn't load in a PBR compatible resourcepack, even with saner fallbacks there'd be close to no point in this shaderpack without them so I won't support it.

what pbr format does it support, labPBR or seusPBR

**Comment by Stehsaer** [comment]
I've tried loading in a PBR resourcepack, but it didn't look better
Tried other PBR resourcepack, none of them works
![image](https://github.com/BalintCsala/VulkaniteDemoPack/assets/54050160/756bbfdc-d0b0-4ca0-a749-b3269b323faa)

before setting /time set day (it's day already)
![2023-09-24_11 54 41](https://github.com/BalintCsala/VulkaniteDemoPack/assets/54050160/06c24ae1-1d88-44dd-ad55-93395165cf5e)
after:

![2023-09-24_11 55 47](https://github.com/BalintCsala/VulkaniteDemoPack/assets/54050160/2b41cf6d-5317-4ce2-8171-901f8ef7a4d1)
![2023-09-24_11 55 57](https://github.com/BalintCsala/VulkaniteDemoPack/assets/54050160/65231f73-07e4-417e-8066-4f14c0a9c74a)

**Comment by Stehsaer** [comment]
![2023-09-24_12 01 15](https://github.com/BalintCsala/VulkaniteDemoPack/assets/54050160/ecab3c76-556e-4ee8-9a01-f2059fd1dd0a)
with another PBR texturepack

**Comment by BalintCsala** [comment]
@Stehsaer vulkanite is currently bugged, restart the game _fully_ every time you load a resourcepack

**Comment by DarianLStephens** [comment]
I had the same issue, and adding the Unity PBR resource pack _sort of_ helped, but there are missing texture (purple+black checkers) sometimes, leaves glow in the dark, and nothing that should emit light does.
Also, as soon as the sun moves from the starting position, the whole world looks like it became night. Takes a few seconds after setting it to day.

![2023-10-03_01 42 59](https://github.com/BalintCsala/VulkaniteDemoPack/assets/15375876/970818ac-81f4-4f24-a5db-b635862f39bb)
![2023-10-03_01 44 00](https://github.com/BalintCsala/VulkaniteDemoPack/assets/15375876/9ecb35f4-afa3-498b-b762-e33e1664264c)
![2023-10-03_01 43 08](https://github.com/BalintCsala/VulkaniteDemoPack/assets/15375876/acb0aac8-407c-4ccd-b84c-2ce10103d180)

**Comment by BalintCsala** [comment]
@DarianLStephens Please don't post into closed issues and don't open a new one with your report, what you posted just is probably just the resourcepack not containing the required information or alternatively vulkanite bugs

**Comment by DarianLStephens** [comment]
Looks like it mostly started working once I switched to VanillaPBR, but the day-night cycle is still weird.
It almost looks like it was greatly sped up by the shader?
