### ISSUE TITLE
Rendering is messed up? 

### ISSUE THREAD

**Issue by Fusion-Flux** [BalintCsala/VulkaniteDemoPack#6]
its kinda hard to explain so ill just send images
![image](https://github.com/BalintCsala/VulkaniteDemoPack/assets/71662169/6662ea9d-aaca-403d-8339-e94288ce4c90)

basically everything ends up super dark and just unviewable ocasionally it is viewable but looks like this

![image](https://github.com/BalintCsala/VulkaniteDemoPack/assets/71662169/efeed9ec-dfe5-44a1-99ac-66d7e73b0a26)

**Comment by Fusion-Flux** [comment]
running on a RTX 3060 doesnt really matter if its on linux or windows ive tested on both it seems to cycle between these viewings its strange

![image](https://github.com/BalintCsala/VulkaniteDemoPack/assets/71662169/69dafadb-690b-4afa-924a-e5bd7e775d7a)

**Comment by DarianLStephens** [comment]
You _require_ a PBR resource pack for this to work.
Unfortunately, this is not mentioned anywhere, merely stated as 'having PBR compatibility'.
I've been using VanillaPBR, and it works pretty well.

Note that the mod and shader are _definitely not ready for general use._
A huge problem is that denoising only seems to exist for sunlight rays, meaning all other light sources will be the raw ray information, appearing as many many incomprehensible dots.

**Comment by BalintCsala** [comment]
@Fusion-Flux As Darian mentioned, this pack needs a resourcpeack, doesn't work without one. This might be adressed in the future, but as long as it's in the tech demo phase don't expect it (not that it would look great either way).

> A huge problem is that denoising only seems to exist for sunlight rays, meaning all other light sources will be the raw ray information, appearing as many many incomprehensible dots.

@DarianLStephens no, everything is denoised

**Comment by DarianLStephens** [comment]
> > A huge problem is that denoising only seems to exist for sunlight rays, meaning all other light sources will be the raw ray information, appearing as many many incomprehensible dots.
> 
> @DarianLStephens no, everything is denoised

Wait, huh? I could definitely be wrong, but this doesn't look denoised:
![2023-10-06_13 11 01](https://github.com/BalintCsala/VulkaniteDemoPack/assets/15375876/41ee63b7-8b25-4521-a59e-7c96162e58f4)

Sunlight, however, looks fine (With the exception of bounced light):
![2023-10-06_13 10 15](https://github.com/BalintCsala/VulkaniteDemoPack/assets/15375876/fb907138-3ad0-4780-814c-19aa9313dac4)

Is there a problem with my game, then, or is this how it's expected to work at the moment?
Or maybe my terminology is wrong, and the whole 'turning rays in to a coherent image' thing isn't what denoising is about?

**Comment by BalintCsala** [comment]
@DarianLStephens Try to load in a dark scene with something other than just a single tiny torch illuminating it, the denoiser is there, it's just not a good one. Alternatively turn reprojection frames down to 1 and see how it affects both scenes.

**Comment by DarianLStephens** [comment]
Looks slightly better, I guess, but still not good.
![2023-10-07_12 49 14](https://github.com/BalintCsala/VulkaniteDemoPack/assets/15375876/a59d9415-fae3-419b-b911-2332f60522e9)
With only a single block of glowstone, it's comparable to the torch:
![2023-10-07_12 49 47](https://github.com/BalintCsala/VulkaniteDemoPack/assets/15375876/87efa118-d326-4cdd-b834-21c6b8627f29)

There's also no 'reprojection frames' option I can see. Is that something in development? I've just got the mod and shader off Modrinth.
![2023-10-07_12 49 58](https://github.com/BalintCsala/VulkaniteDemoPack/assets/15375876/a0155b50-8f4a-4792-b6f5-d925a82b6962)

**Comment by BalintCsala** [comment]
@DarianLStephens meant reprojection length

**Comment by DarianLStephens** [comment]
Ah.
Well, I tried turning down the 'Accumulation length', but that seemed to make the whole image more unstable, and killed lights for the most part.

**Comment by BalintCsala** [comment]
@DarianLStephens Yes, that's the effect of the very weak denoiser in there right now, it just has a better time with direct lighting because rays are simply more likely to hit the sun

**Comment by DarianLStephens** [comment]
I see, I see.
Well, I look forward to seeing future developments in the shader and Vulkanite as a whole.
I saw some merges being done, quite exciting.

When the whole system is in a playable state, I will likely never touch Bedrock again. RTX is the only reason I even consider playing it sometimes, and even then I always run it on a Java server with Geyser and some server-side mods.

**Comment by Fusion-Flux** [comment]
Sorry forgot about this post completely. using pbr i still experience simular issues though rarely i can boot and it just works
![image](https://github.com/BalintCsala/VulkaniteDemoPack/assets/71662169/8d5c292c-c4c6-40d5-a700-b72fc167f494)

**Comment by Fusion-Flux** [comment]
had to use infinite accumulation to get the right effect but you get it it mostly works

**Comment by Fusion-Flux** [comment]
The usual effect i consistantly get is just everything being strangely dark
![image](https://github.com/BalintCsala/VulkaniteDemoPack/assets/71662169/b22c51e1-5681-4241-af20-190e75b57f1c)
