### ISSUE TITLE
weird dots all over the screen

### ISSUE THREAD

**Issue by netflexy** [BalintCsala/VulkaniteDemoPack#7]
You _must_ include the following details:

- every time i load the shader, can be reproduced everytime. when i walk, dots get bigger. When i change resolution, 2-3 dots in the screen and shrinked.
-![image](https://github.com/BalintCsala/VulkaniteDemoPack/assets/114685552/d194ccba-5469-48af-bd3a-cf3dc560c90d)
- rtx 3050 laptop (GameReady driver 537.42)
  ryzen 5 5000
  12gb ram

**Comment by netflexy** [comment]
also lightning exept lava doesn't work

**Comment by netflexy** [comment]
Lightning doesn't work, it's set to sertain value, and doesnt change exept from where reflections go.

**Comment by BalintCsala** [comment]
You need a PBR capable resourcepack for the shader to work

**Comment by netflexy** [comment]
wich one?

**Comment by netflexy** [comment]
> Owner

wich texturepack?
