### ISSUE TITLE
[BUG]: Artifacts

### ISSUE THREAD

**Issue by dam2452** [BalintCsala/VulkaniteDemoPack#8]
![2023-10-26_13 19 52](https://github.com/BalintCsala/VulkaniteDemoPack/assets/81230036/79de8c57-e709-40e3-b766-cc492db97817)
![2023-10-26_13 19 54](https://github.com/BalintCsala/VulkaniteDemoPack/assets/81230036/654eb636-f2ee-4f8c-b9f4-74f346234eb9)
![2023-10-26_13 19 53](https://github.com/BalintCsala/VulkaniteDemoPack/assets/81230036/92fb3471-0356-401b-909a-8df6481a17bf)

Issue Description:
I'm experiencing a consistent issue every time I run Minecraft across all worlds.

System Specifications:
CPU: R9 3900x
RAM: 32GB
GPU: RTX 2080 Super

Software Versions:
Minecraft: 1.20.1 (MultiMC)
Fabric: 0.14.23
Iris: 1.6.8
Sodium: 0.5.2
Vulkanite: 0.0.3 pre-alpha
Shader: Vulkanite Demo Pack v1.3.0
NVIDIA Driver: 545.84
OS: Windows 11 22h2 (22621.2428)

If I forgot about something, you can write to me and I will provide you with other data, logs, or even the entire MultiMC instance.

**Comment by BalintCsala** [comment]
![image](https://github.com/BalintCsala/VulkaniteDemoPack/assets/33815391/e2b83373-0362-4e66-9465-56ef8412765e)

**Comment by dam2452** [comment]
![image](https://github.com/BalintCsala/VulkaniteDemoPack/assets/81230036/57888a33-e682-4268-bf8d-a8d95d2fa2de)
I tested these texture packs and it's still the same.

**Comment by BalintCsala** [comment]
@dam2452 make sure to select the resourcepack in-game, then completely close out of it and restart it, vulkanite is currently bugged, you can't reload resourcepacks without restarting the game. The issue is almost definitely coming from this

**Comment by dam2452** [comment]
I set the texture pack to DefaultPBR, then restarted the game twice, and it seems better, but I'm not sure if that was the intended effect.
![2023-10-30_11 58 59](https://github.com/BalintCsala/VulkaniteDemoPack/assets/81230036/e821c09a-7348-4b1b-a428-f3a28fb7e232)
![2023-10-30_12 00 30](https://github.com/BalintCsala/VulkaniteDemoPack/assets/81230036/d831299f-31b2-47f3-8899-ee7b1b35e510)
![Base Profile Screenshot 2023 10 30 - 11 55 22 18](https://github.com/BalintCsala/VulkaniteDemoPack/assets/81230036/f1ade709-1859-4ccf-8e45-adb93b6f1d6d)
![2023-10-30_12 00 33](https://github.com/BalintCsala/VulkaniteDemoPack/assets/81230036/ae557002-a5f6-43cc-9271-540fc2b74939)

**Comment by BalintCsala** [comment]
@dam2452 That looks perfectly fine, keep in mind this pack is very much in development, the latest available version only had a about a week's worth of free time put into it
