### ISSUE TITLE
[BUG]: Screen displays nothing

### ISSUE THREAD

**Issue by minaLogi** [BalintCsala/VulkaniteDemoPack#9]
I cloned latest Vulkanite mod and VDP, I am testing on InteliJ IDEA's debug environment.
When I turned on VulkaniteDemoPack, It displays blank screen. Looking at the debug information, SSBOs seem to be uploaded correctly by Vulkanite mod.

![2024-01-07_10 45 05](https://github.com/BalintCsala/VulkaniteDemoPack/assets/88201103/7a3bd975-ec06-4eae-af1e-409f23bca562)
![2024-01-07_10 45 27](https://github.com/BalintCsala/VulkaniteDemoPack/assets/88201103/6920e6fd-84e4-435a-9898-02b9dce37624)
<img width="455" alt="image" src="https://github.com/BalintCsala/VulkaniteDemoPack/assets/88201103/1228fc87-3189-4075-b258-dea06edafb77">

my PC spec:
- Core i7 12700F
- DDR4 3200 32GB
- Geforce RTX 3050 8GB

**Comment by BalintCsala** [comment]
The publicly available version of VulkaniteDemoPack only works with the latest release of Vulkanite (0.0.3) because of pipeline changes. Make sure you use this pairing.

**Comment by minaLogi** [comment]
I am using Vulkanite and VDP cloned from the Github master branch.
Are you saying that the current VDP will not work even if combined with Vulkanite 0.0.4-pre-alpha?

**Comment by BalintCsala** [comment]
@minaLogi Yes, that's exactly what my previous message said.

**Comment by minaLogi** [comment]
I understand. I look forward to the development of this shader.
